### PR TITLE
Deprecate getURL()

### PR DESCRIPTION
**Pull request by offa**
Deprecate `getURL()` in favour of `getUrl()`, see #54.

----------------------------------------

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by jmMeessen — COMMENTED** [review]
I wonder how this renders when running a pipeline. Does it show a warning message in the log file?

**Comment by offa** [comment]
(Without actually knowing the answer) I don't think so, I'd expect it as development related only. At least I haven't seen any deprecation notices yet.

**Comment by jmMeessen** [comment]
I researched it on my side. The deprecation notice will not give a warning in the pipeline. And I didn't see another elegant way to do it.

So what do you think of the following proposition:
* remove the "breaking change" tag on the PR and tag it as "chore" instead (impact on release notes) (Jmm)
* leave the `@deprecated` annotation 👍  (and not remove that getter as this is a riffle too violent) (no action)
* add a note to the readme telling that to retrieve the URL, either `hook.url`  or `hook.getUrl()` can be used. `getURL()` is deprecated and will be removed in the future. (offa?)

If you agree, could you add such information in the README?

**Comment by offa** [comment]
Sounds good! :+1: 

I'm going to update the readme.

**Comment by offa** [comment]
Added (+ syntax coloring).

Examples are up-to-date already.

**Comment by jmMeessen** [comment]
Excellent work. Thank you very much @offa

**Pull request merged**
