### PR TITLE
Update to Jenkins 2.361 LTS

### PR DESCRIPTION
**Pull request by offa**
Update to Jenkins 2.361 LTS ([context](https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.52)).

-------------------------

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by offa** [comment]
@jmMeessen the Jenkinsfile needs an update too (an older LTS version is used), but this requires someone with write permissions.

**Comment by jmMeessen** [comment]
@offa 
Do we agree that the modification to the Jenkinsfile is to remove the "jenkins: '2.342'" on the java 17 build ?

**Comment by offa** [comment]
Yes, only the `jenkins: '2.342'` is relevant.

**Review by jmMeessen — APPROVED** [review]
LGTM !

Thank you for the contribution, @offa .

**Pull request merged**
